openapi: 3.0.0
info:
  title: Conjury API
  version: '1.0'
  contact:
    email: hello@conjury.io
    url: 'https://conjury.io'
  description: ''
servers:
  - url: 'https://api.conjury.io'
paths:
  /v1/token:
    post:
      summary: Create Token
      tags:
        - Token
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
      operationId: post-v1-token
      description: |-
        Endpoint to create a login token that can then be consumed in the future.

        Optional context can be passed to assist you in identifying the user once the token is consumed.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                identifier:
                  type: string
                context:
                  type: object
              required:
                - identifier
      parameters: []
  '/v1/token/{token}':
    parameters:
      - schema:
          type: string
        name: token
        in: path
        required: true
    post:
      summary: Consume Token
      tags:
        - Token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                  context:
                    type: object
      operationId: post-v1-token-token
      description: 'Endpoint to consume a given token, will return all user data passed when originally creating the token.'
      requestBody: {}
components:
  schemas: {}
